Stackoverlow - more functionality
P5CHI-Web-Academy/Homework-VueJS pull request #11
Opened 2019-05-27 12:31 UTC by oladelmar

Added search by questions, users and tags.
Search results are displayed but not styled.

I guess there is a more elegant way to do that. I just haven't found it yet)

2019-05-27 15:17 UTC, gregurco requested changes

2019-05-27 15:17 UTC, gregurco commented on src/components/Questions/Questions.vue
> +              <router-link :to="{name: 'question', params: {id: question.id}}">
Please check this rule: https://eslint.org/docs/rules/key-spacing

2019-05-27 15:17 UTC, gregurco commented on src/store/modules/results.js
> +          console.log(result.data)
remove `console.log`

2019-05-30 12:56 UTC, rapi requested changes
Good job, just some logic changes

2019-05-30 12:56 UTC, rapi commented on src/api/questions.js
> +export const fetchQuestions = (params) => API.get(`/questions${params}`)
Axios have params, dont send it via string

2019-05-30 12:56 UTC, rapi commented on src/api/search.js
> +export const fetchUsersSearchResults = (param) => API.get('/users?q='+ param)
No string params

2019-05-30 12:56 UTC, rapi commented on src/router/router.js
> +          props: (route) => ({ query: route.query.q }),
props: true

2019-05-30 12:56 UTC, rapi commented on src/store/modules/questions.js
> +        })
make con catch on every request

2019-05-30 12:56 UTC, rapi commented on src/store/modules/results.js
> +import { fetchQuestionsSearchResults, fetchUsersSearchResults, fetchTagsSearchResults } from '@/api/search'
you dont need this module, access the module(user, question) directly

2019-05-30 12:56 UTC, rapi commented on src/store/modules/users.js
> +        })
catch

2019-05-30 12:56 UTC, rapi commented on src/views/AllSearchResults.vue
> +      resultQuestionsList: 'results/getResultQuestionsList',
dont use general module, access the module directly

2019-06-15 11:17 UTC, merged