Asisov - homework
P5CHI-Web-Academy/Homework-VueJS pull request #5
Opened 2019-05-13 12:42 UTC by anek77713

2019-05-13 13:14 UTC, gregurco requested changes

2019-05-13 13:14 UTC, gregurco commented on .eslintrc.js
> +    'eslint:recommended'
what about standard js style guide?

2019-05-13 13:14 UTC, gregurco commented on package.json
> +  "name": "www",
please rename the project

2019-05-15 07:02 UTC, anek77713 commented on .eslintrc.js
> +    'eslint:recommended'
done

2019-05-15 07:02 UTC, anek77713 commented on package.json
> +  "name": "www",
done

2019-05-15 07:21 UTC, merged